# Generated by Django 5.1.6 on 2025-03-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interested_volunteers', to='backend.interest'),
        ),
    ]
