# Generated by Django 5.1.6 on 2025-02-15 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='current_colunteers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='end_time',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='estimated_duration',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='estimated_effort_ranking',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 14, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='start_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='last_completion',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 14, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='opportunities_completed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
