# Generated by Django 5.1.6 on 2025-02-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_opportunity_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='last_completion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='opportunities_completed',
            field=models.IntegerField(default=0),
        ),
    ]
