# Generated by Django 5.1.6 on 2025-03-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_volunteer_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('requesting_complete', 'Request Completion'), ('completed', 'Completed'), ('not_completed', 'Not Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='interested_volunteers', to='backend.interest'),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_person', models.CharField(max_length=50)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=1024)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.volunteer')),
            ],
        ),
    ]
