# Generated by Django 5.1.6 on 2025-02-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_volunteer_last_completion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='interested_volunteers', to='backend.interest'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
