# Generated by Django 5.1.6 on 2025-03-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_application_status_alter_volunteer_interests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='hours',
        ),
    ]
