# Generated by Django 5.1.6 on 2025-03-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_volunteer_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='automatic_accepting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='interests', to='backend.interest'),
        ),
    ]
