# Generated by Django 5.1.6 on 2025-02-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_volunteer_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='current_volunteers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='opportunities', to='backend.category'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
