# Generated by Django 5.1.6 on 2025-02-17 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_application_current_volunteers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='current_colunteers_count',
            new_name='current_volunteers_count',
        ),
    ]
