# Generated by Django 5.1.6 on 2025-02-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_current_colunteers_count_opportunity_current_volunteers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='display_name',
            field=models.CharField(default='', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
