# Generated by Django 5.1.6 on 2025-03-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='answer',
            field=models.TextField(max_length=2048, null=True),
        ),
    ]
