# Generated by Django 5.1.6 on 2025-02-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_volunteer_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='categories',
            field=models.ManyToManyField(related_name='opportunities', to='backend.category'),
        ),
    ]
