# Generated by Django 5.1.6 on 2025-03-18 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_discussion_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.opportunity'),
        ),
    ]
