# Generated by Django 5.1.6 on 2025-02-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_volunteer_animals_score_volunteer_community_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='hours',
            field=models.IntegerField(default=0),
        ),
    ]
