# Generated by Django 5.1.6 on 2025-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_discussion_time_created_alter_discussion_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='name_share_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='answer',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
