# Generated by Django 5.1.6 on 2025-02-23 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_opportunity_categories'),
        ('backend', '0009_volunteer_hours'),
    ]

    operations = [
    ]
