# Generated by Django 5.1.6 on 2025-03-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_volunteer_name_share_public_alter_discussion_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='public_friends',
            field=models.BooleanField(default=False),
        ),
    ]
